# Generated by Django 3.2.16 on 2022-12-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app_core', '0001_initial'), ('app_core', '0002_coin'), ('app_core', '0003_rename_coin_currency'), ('app_core', '0004_user_e_mail'), ('app_core', '0005_user_name'), ('app_core', '0006_user_test010'), ('app_core', '0007_auto_20221120_2037'), ('app_core', '0008_bankcurrency_merchant_usercurrency'), ('app_core', '0009_auto_20221120_2156'), ('app_core', '0010_auto_20221121_0125'), ('app_core', '0011_auto_20221121_0128'), ('app_core', '0012_administrator'), ('app_core', '0013_administrator_access_control_list'), ('app_core', '0014_voucher'), ('app_core', '0015_auto_20221122_0256'), ('app_core', '0016_auto_20221122_0343'), ('app_core', '0017_alter_userbalance_balance'), ('app_core', '0018_auto_20221123_1451'), ('app_core', '0019_auto_20221123_1555'), ('app_core', '0020_rename_token_user_bank_user_payment_id'), ('app_core', '0021_aeskeyverify'), ('app_core', '0022_auto_20221127_1146'), ('app_core', '0023_digitalwallet'), ('app_core', '0024_alter_digitalwallet_encrypted_currency'), ('app_core', '0025_alter_usedcurrency_message'), ('app_core', '0026_transactionlog'), ('app_core', '0027_transactionlog_status'), ('app_core', '0028_transactionlog_message')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField(default=0)),
                ('address', models.CharField(default='Address', max_length=100)),
                ('name', models.CharField(default='Name', max_length=100)),
                ('owner', models.CharField(default='Owner', max_length=100)),
                ('phone', models.CharField(default='05xxxxxxx', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField(default=0)),
                ('coin_seq', models.CharField(default='coin_seq', max_length=100)),
                ('sign_coin_seq', models.CharField(default='sign_coin_seq', max_length=100)),
                ('spend_check', models.BooleanField(default=False)),
                ('user_id', models.CharField(default='user_id', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=100)),
                ('access_control_list', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField()),
                ('voucher_token', models.CharField(max_length=100)),
                ('is_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=100)),
                ('e_mail', models.CharField(max_length=100, null=True)),
                ('home_address', models.CharField(default='Address', max_length=100, null=True)),
                ('phone', models.CharField(default='09xxxxxxxx', max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('bank_user_payment_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AESKeyVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('aes_key_verify_ciphertext', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('encrypted_currency', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UsedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('Info', models.CharField(max_length=100)),
                ('R', models.CharField(max_length=100)),
                ('s', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('used_currency', models.CharField(max_length=1000, null=True)),
                ('status', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
