# Generated by Django 3.2.16 on 2022-12-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_squashed_0028_transactionlog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='withdraw_amount',
            field=models.IntegerField(null=True),
        ),
    ]
