# Generated by Django 3.2.16 on 2022-12-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_transactionlog_withdraw_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='withdraw_amount',
            new_name='amount',
        ),
    ]
